# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)


# Отправлять уведомление на почту bodins@yandex.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -bodins@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    CODECOV_TOKEN="13696318-9bf9-4d6d-8f6b-f45c11eeb540"
